### ISSUE TITLE
IOC

### ISSUE THREAD

**Issue by szyhf** [szyhf/DIServer#4]
总算把多例弄出来了。。。
下一步是继续测试可靠性。。

**Comment by szyhf** [comment]
...这次提交的代码好像有问题。。怎么跟我本地的版本不一样。。

**Comment by szyhf** [comment]
中间件

前置装饰器
处理器 - 事件
后置装饰器
任务队列
配置
服务

会话组件
缓存组件
日志组件
ORM

看起来。。。囧怎么好像还是差不少东西=。=

**Comment by weijer** [comment]
加油~
