### ISSUE TITLE
引入了Composer

### ISSUE THREAD

**Issue by szyhf** [szyhf/DIServer#5]
所以计划中这个项目会在第一期分为三块
[ThinkPHP for DIServer](https://github.com/szyhf/thinkphp)
[DIServer Framework](https://github.com/szyhf/DIServer)
[DIServer Project](https://github.com/szyhf/DIServerProject)
Framework是组织工具和主要业务流程的，Project是调用Framework的，ThinkPHP作为前期提供一定业务工具或者服务的第三方库（如ORM）。
Framework本身将不会依赖于ThinkPHP。

**Comment by weijer** [comment]
有使用教程么

**Comment by szyhf** [comment]
正在重构，重构完我会更新wiki的~

**Comment by weijer** [comment]
好的 给力
