### ISSUE TITLE
Notes 

### ISSUE THREAD

**Issue by szyhf** [szyhf/DIServer#6]
# Note 20151205

一开始上传这个框架的时候，我其实已经在项目中用了一段时间了，所以肯定是可用的，但因为工作原因，很多时候为了赶进度，有些
地方总觉得做得并不理想（例如ThinkPHP面向web网站开发的特性导致很多冗余的代码被加载的），总想着上传以后，把这些小地方改>完善了，在加入使用的方法，结果发现，一方面最近工作实在太忙，感觉人的精力实在兼顾不来；另一方面，在调整的过程中发现问题
越改越多，想法纷纷扰扰，拔剑四顾心茫然。
饭要一口口吃，事情要一点点做，感觉自己还是有很多的不足希望改进。以前做项目的时候总被老板批说不出产品，老想着把东西做完
善了再交，客户不等人的。

不知道github上会不会这样，这个框架对我而言，还有特别的意义，我还是会继续往下做好它的。

计划要做的事情：
- 加入DI控制，正在研究Laravel的Container工具和.Net的SimpleIOC，但不打算把整个Laravel引进来，也不打算把功能做的那么强大
  ，过度灵活的松耦合对于一个目的明确的框架而言，我认为是一种过度设计，我不希望把这个框架做得太臃肿，也不需要它太强大，它
  只要能快速的解决核心的问题即可，提供合适的基础功能以后，更多的自由度交给使用者（其实我正在做）。
- 另外我不打算把它做成能支持http等应用层协议的框架，所以类似路、View由等东西，我会着手砍掉。
- 目前我的理解和期望是，允许你来制定应用层协议（当然，我会提出一些约定，不可能满足所有人的口味，我更倾向于专注于别的地
  方）。当然，在这个基础上，有需要的可以自己改进。

希望这样可以改善整个程序的耦合性。
希望这不是过度设计。

**Comment by szyhf** [comment]
# Note 20151224

又是一年的平安夜，好吧，回首一下感觉恍若隔世。
最近的主要工作在参考Lavarel的框架重构一部分业务流程。
当然，Lavarel是面向http服务为主的，很多机制并不完全合适。
我还在计划把ThinkPHP从框架中拆出来，仅作为一个可选的ORM工具提供者。
加油吧~Good Luck

**Comment by szyhf** [comment]
# Note 20160112

转眼间来到新的一年，为啥最近没更新呢。。。
最近一直在写文档Orz，另外有些调用的方式还不是太理想

**Comment by weijer** [comment]
啥时候发布第一版

**Comment by szyhf** [comment]
估计还要。。。。。现在ORM的问题还没想通。。。

**Comment by weijer** [comment]
方便加qq么 想请教swoole 问题！ 我的QQ250557277

**Comment by szyhf** [comment]
Swoole开发组QQ群：#3群 472153539，与swoole的使用者和开发者进行交流
group.swoole.com  swoole问答社区

**Comment by weijer** [comment]
群里面没人鸟我啊~ 问题估计对于大牛们 太无语了！ swoole_client 在cli模式下可以运行！ 在apache下面运行 页面出错 （用的同步模式）！ apache是需要什么特需配置么？

**Comment by szyhf** [comment]
噢，我想我知道你是谁了。。
这个问题我不知道怎么回事哦，我这里可以正常用无压力。。

**Comment by weijer** [comment]
用的也是apache2.4+php7 么？ 能推荐个编译安装文章么~

**Comment by szyhf** [comment]
噢，那个机子是php5.5吧，php7还真没试过，我调试php7的机子没有装apache



yhf_szb@qq.com
 
From: weijer
Date: 2016-02-24 09:38
To: szyhf/DIServer
CC: Back
Subject: Re: [DIServer] Notes (#6)
用的也是apache2.4+php7 么？ 能推荐个编译安装文章么~ 
―

**Comment by weijer** [comment]
重新安装了下apache 可以了
